Repository GarnBarn/garnbarn-frontend, pull requests merged in 2021-11, with the labels that each got.

#23 Assignment Creation
  README.md
  package.json
  src/components/AssignmentDetail.vue
  src/components/AssignmentEdit.vue
  src/components/Create.vue
  src/layouts/Main.vue
  src/router/index.ts
  src/services/GarnBarnApi/apis/v1/AssignmentApis.ts
  src/services/GarnBarnApi/apis/v1/TagApis.ts
  src/types/GarnBarnApi/AssignmentApi.ts
  src/types/GarnBarnApi/GarnBarnApiResponse.ts
  src/views/Assignment/AssignmentDetailView.vue
  src/views/Assignment/Assignments.vue
  src/vue2-datepicker.d.ts
  yarn.lock
Labels: enhancement

#31 Subscribe/Unsubscribe Tag
  src/components/Tag/TagSubscribe.vue
  src/services/GarnBarnApi/apis/v1/TagApis.ts
  src/types/GarnBarnApi/TagApi.ts
  src/views/Tag/Tags.vue
Labels: enhancement

#38 Change CI
  .github/workflows/test.yml
  .travis.yml
  README.md
Labels: P0

#37 Assignment/Tag Detail Page
  src/components/Create.vue
  src/components/DetailCard.vue
  src/views/Account/Account.vue
  src/views/Assignment/AssignmentDetailView.vue
  src/views/Assignment/Assignments.vue
  src/views/Tag/TagDetailView.vue
  src/views/Tag/Tags.vue
Labels: enhancement

#41 Improve notification setting
  src/components/Assignment/AssignmentBox.vue
  src/components/Assignment/AssignmentDetail.vue
  src/components/Assignment/DateWithAssignment.vue
  src/components/Create.vue
  src/components/NotificationSetting.vue
  src/components/Tag/TagDetail.vue
  src/types/GarnBarnApi/AssignmentApi.ts
  src/types/garnbarn/Assignment.ts
  src/views/Assignment/AssignmentDetailView.vue
  src/views/Assignment/Assignments.vue
  src/views/Home.vue
  src/views/Tag/TagDetailView.vue
  tests/unit/Components/AssignmentBox.spec.ts
  tests/unit/Components/AssignmentDetail.spec.ts
  tests/unit/Components/DateWithAssignment.spec.ts
  tests/unit/Components/Tag/TagDetail.spec.ts
Labels: enhancement

#51 Hotfix: Fixed text field length
  src/components/Assignment/AssignmentDetail.vue
  src/components/Create.vue
  src/layouts/Main.vue
Labels: bug
